apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: projectcontour-internal
  namespace: projectcontour-internal
spec:
  releaseName: projectcontour-internal
  maxHistory: 3
  skipCRDs: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: contour
    version: "3.0.0"
  values:
    envoy:
      image:
        repository: envoyproxy/envoy
        tag: v1.16.0
      useHostPort: false
      containerPorts:
        http: 8080
        https: 8443
      service:
        loadBalancerIP: 192.168.93.83
      containerSecurityContext:
        runAsUser: 1001
    contour:
      image:
        repository: projectcontour/contour
        tag: v1.10.0

    prometheus:
      serviceMonitor:
        enabled: true
