apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: projectcontour-internal
  namespace: projectcontour-internal
spec:
  releaseName: projectcontour-internal
  maxHistory: 3
  install:
    skipCRDs: true
  interval: 5m
  chart:
    spec:
      chart: contour
      version: "3.2.0-defaultbackend.0"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-local-charts
        namespace: flux-system
      interval: 1m
  values:
    envoy:
      image:
        repository: envoyproxy/envoy
        tag: v1.16.0
      useHostPort: false
      containerPorts:
        http: 8080
        https: 8443
      service:
        loadBalancerIP: 192.168.93.83
      containerSecurityContext:
        runAsUser: 1001
    contour:
      image:
        repository: projectcontour/contour
        tag: v1.10.0

    prometheus:
      serviceMonitor:
        enabled: true

    defaultBackend:
      enabled: true

      image:
        registry: k8s.gcr.io
        repository: defaultbackend-amd64
        tag: "1.5"

      livenessProbe:
        httpGet:
          path: /healthz
      readinessProbe:
        httpGet:
          path: /healthz
