---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 2.22.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        config:
          region: minio
          s3ForcePathStyle: true
          s3Url: https://s3.ma.kilchhofer.info
      volumeSnapshotLocation:
        name: aws
        config:
          region: minio
      resticTimeout: 6h
    credentials:
      useSecret: true
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
        cpu: 1
    securityContext:
      runAsNonRoot: true
      runAsGroup: 65534
      runAsUser: 65534
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
    deployRestic: true
    installCRDs: true
    restic:
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 2000Mi
    schedules:
      daily:
        schedule: "10 6 * * *"
        template:
          ttl: "360h"
  valuesFrom:
  - kind: Secret
    name: "velero-values"
    valuesKey: secretContents_cloud
    targetPath: credentials.secretContents.cloud
