---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium-charts
  namespace: kube-system
spec:
  interval: 10m
  url: https://helm.cilium.io/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: kube-system
      interval: 1m
  values:
    rollOutCiliumPods: true
    operator:
      replicas: 1
      rollOutPods: true
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    ipam:
      mode: kubernetes
    hubble:
      relay:
        enabled: true
        rollOutPods: true
        resources:
          limits:
            cpu: 1000m
            memory: 1024M
          requests:
            cpu: 100m
            memory: 64Mi
      ui:
        enabled: true
        rollOutPods: true
        backend:
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
            requests:
              cpu: 100m
              memory: 64Mi

        frontend:
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
            requests:
              cpu: 100m
              memory: 64Mi

      tls:
        auto:
          method: certmanager
          certManagerIssuerRef:
            group: cert-manager.io
            kind: ClusterIssuer
            name: ca-issuer
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 300m
        memory: 300Mi
