---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: "5.6.0-1"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-local-charts
        namespace: flux-system
      interval: 1m
  values:
    apiService:
      create: true

    image:
      registry: k8s.gcr.io
      repository: metrics-server/metrics-server
      tag: v0.4.2

    command: ""
    extraArgs:
      cert-dir: /tmp
      kubelet-preferred-address-types: InternalIP,ExternalIP,Hostname
      kubelet-use-node-status-port: {}

    extraVolumeMounts:
      - mountPath: /tmp
        name: tmpdir

    extraVolumes:
      - name: tmpdir
        emptyDir: {}

    priorityClassName: system-cluster-critical

    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 10m
        memory: 30Mi

    containerSecurityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
