---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: "5.5.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1m
  values:
    apiService:
      create: true

    extraArgs:
      cert-dir: /tmp
      kubelet-preferred-address-types: InternalIP,ExternalIP,Hostname
      kubelet-use-node-status-port: {}

    extraVolumeMounts:
      - mountPath: /tmp
        name: tmpdir

    extraVolumes:
      - name: tmpdir
        emptyDir: {}

    priorityClassName: system-cluster-critical

    resources:
      requests:
        cpu: 10m
        memory: 30Mi
