---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: "5.5.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      registry: k8s.gcr.io
      repository: metrics-server/metrics-server
      tag: v0.4.1
