apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: "1.15.0-r3"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 1m
  values:
    crd:
      create: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: contour
        ingress.kubernetes.io/force-ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - sealed-secrets.tools.kilchhofer.info
      tls:
        - hosts:
          - sealed-secrets.tools.kilchhofer.info
          secretName: sealed-secrets-cert
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 10m
        memory: 30Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealed-secrets-view
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/instance: sealed-secrets
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - get
      - list
      - watch
