apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: "1.10.3"
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      interval: 1m
  values:
    crd:
      create: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: contour
        ingress.kubernetes.io/force-ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - sealed-secrets.tools.kilchhofer.info
      tls:
        - hosts:
          - sealed-secrets.tools.kilchhofer.info
          secretName: sealed-secrets-cert
