apiVersion: v1
kind: Namespace
metadata:
  name: traefik-internal
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik-internal
spec:
  releaseName: traefik-internal
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: "1.79.0"
  values:
    rbac:
      enabled: "true"
    loadBalancerIP: "192.168.93.89"
    imageTag: "1.7.20"
    externalTrafficPolicy: Local
    traefikLogFormat: "json"
    accessLogs:
      enabled: "true"
      fields:
        names:
          BackendURL: drop
          ClientAddr: drop
          StartLocal: drop
        headers:
          defaultMode: drop
      format: json
    acme:
      enabled: "true"
      challengeType: "dns-01"
      delayBeforeCheck: 15
      dnsProvider:
        name: cloudflare
        cloudflare:
          CF_API_EMAIL: "marco.kilchhofer@gmail.com"
          CF_API_KEY: "<Cloudflare Global API Key>"
      domains:
        domainsList:
          main: "*.tools.kilchhofer.info"
      email: "postmaster@kilchhofer.info"
      logging: true
      staging: false
    dashboard:
      enabled: true
      domain: traefik.tools.kilchhofer.info
      ingress:
        annotations:
          kubernetes.io/ingress.class: traefik-internal
          traefik.ingress.kubernetes.io/redirect-entry-point: https
    kubernetes:
      ingressClass: traefik-internal
      ingressEndpoint:
        useDefaultPublishedService: "true"
    ssl:
      enabled: "true"
      enforced: "true"
      insecureSkipVerify: "true"
      sniStrict: "true"
