apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
  namespace: logging
spec:
  fluentd:
    disablePvc: true
  fluentbit:
    positiondb:
      hostPath:
        path: "" # leave it empty to automatically generate
  controlNamespace: logging

