apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: syslog-rfc3164
  namespace: logging
spec:
  releaseName: syslog-rfc3164
  rollback:
    enable: true
  chart:
    repository: https://fluent.github.io/helm-charts
    name: fluent-bit
    version: "0.7.1"
  values:
    serviceAccount:
      create: false
    rbac:
      create: false

    kind: Deployment

    image:
      repository: grafana/fluent-bit-plugin-loki
      tag: 1.6.1-amd64

    extraPorts:
      - name: syslog
        containerPort: 5140
        protocol: TCP
        port: 5140

    config:
      inputs: |
        [INPUT]
            Name syslog
            Parser syslog-rfc3164
            Mode tcp
            Port 5140

      outputs: |
        [OUTPUT]
            Name  stdout
            Match *
    
        [OUTPUT]
            Name  loki
            Match *
            Url http://loki-test.logging.svc:3100/loki/api/v1/push
            TenantID syslog-rfc3164
            LogLevel warn
            LineFormat json
            Labels {job="fluent-bit-syslog-rfc3164"}
            LabelKeys pri,host,ident
            RemoveKeys time,pid
    
      filters: ""
    
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.93.85
