apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging-operator
  namespace: logging
spec:
  releaseName: logging-operator
  interval: 5m
  chart:
    spec:
      chart: logging-operator
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-charts
        namespace: flux-system
      interval: 1m
  values:
    createCustomResource: false
