apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
 name: loki-output
spec:
 loki:
   url: http://loki-s3.logging.svc.cluster.local:3100
   configure_kubernetes_labels: true
   line_format: json
   buffer:
     timekey: 1m
     timekey_wait: 30s
     timekey_use_utc: true
