apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: logging
spec:
  releaseName: loki-stack
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: "2.3.1"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      enabled: false

    loki:
      enabled: false
      service:
        port: 3100

    promtail:
      rbac:
        create: false
        pspEnabled: false
      volumes:
      - name: pods
        hostPath:
          path: /var/log/pods
      - name: varlibpromtail
        hostPath:
          path: /var/lib/promtail
      volumeMounts:
      - name: pods
        mountPath: /var/log/pods
        readOnly: true
      - name: varlibpromtail
        mountPath: /var/lib/promtail
      config:
        positions:
          filename: /var/lib/promtail/positions.yaml
      pipelineStages:
      - cri: {}
