apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 1m
  values:
    rbac:
      create: false
      pspEnabled: false
    loki:
      serviceName: loki.base-infra
    volumes:
    - name: pods
      hostPath:
        path: /var/log/pods
    - name: varlibpromtail
      hostPath:
        path: /var/lib/promtail
    volumeMounts:
    - name: pods
      mountPath: /var/log/pods
      readOnly: true
    - name: varlibpromtail
      mountPath: /var/lib/promtail
    config:
      positions:
        filename: /var/lib/promtail/positions.yaml
    pipelineStages:
    - cri: {}
