apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  maxHistory: 3
  rollback:
    enable: false
  chart:
    repository: https://charts.longhorn.io
    name: longhorn
    version: "1.0.1"
  values:
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2
    defaultSettings:
      backupTarget: s3://longhorn-backup@us-east-1/
      backupTargetCredentialSecret: s3-creds-longhorn
