apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  releaseName: fluent-bit
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: fluent-bit
    version: "2.8.0"
  values:
    image:
      fluent_bit:
        tag: 1.4.2-debug
    backend:
      type: es
      es:
        host: logsene-receiver.eu.sematext.com
        port: 443
        logstash_prefix: null
        logstash_format: "Off"
        replace_dots: null
        index: <INSERT_TOKEN_HERE>
        tls: "on"
        type: logsene_type
    input:
      tail:
        parser: cri
    service:
      flush: 5
      logLevel: info
    metrics:
      enabled: true
    extraEntries:
      filter: |-
        Annotations         Off
        Labels              Off
    trackOffsets: true
    taildb:
      directory: /var/lib/fluent-bit
