---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "2.15.0-1.readOnlyRootFilesystem"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-local-charts
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: false

    controller:
      enableStatefulSet: true
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi

    dex:
      enabled: false

    redis:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi

    repoServer:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi

    server:
      extraArgs:
        - --insecure
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: contour
          ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt
        hosts: ["argocd.tools.kilchhofer.info"]
        tls:
          - secretName: argocd-tls
            hosts: ["argocd.tools.kilchhofer.info"]
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi

      config:
        url: https://argocd.tools.kilchhofer.info
        repositories: |
          - name: services-testing
            sshPrivateKeySecret:
              key: sshPrivateKey
              name: argocd-private-keys
            type: git
            url: git@192.168.93.88:3001/mkilchhofer/k8s-services-testing.git
          - name: k8s-gitops-services
            sshPrivateKeySecret:
              key: sshPrivateKey
              name: argocd-private-keys
            type: git
            url: git@github.com:mkilchhofer/k8s-gitops-services.git

      additionalApplications:
        - name: k8s-gitops-services
          namespace: argocd
          destination:
            server: 'https://kubernetes.default.svc'
          project: base
          syncPolicy:
            automated: {}
          source:
            path: argocd
            repoURL: 'git@github.com:mkilchhofer/k8s-gitops-services.git'
            targetRevision: main
            directory:
              recurse: true

      additionalProjects:
        - name: base
          namespace: argocd
          description: Projects provisioned together with Argo CD (infra deployment)
          clusterResourceWhitelist:
          - group: '*'
            kind: '*'
          destinations:
          - namespace: '*'
            server: 'https://kubernetes.default.svc'
          sourceRepos:
          - '*'

    configs:
      knownHosts:
        data:
          ssh_known_hosts: |
            bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
            github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
            gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
            gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
            ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
            vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
            [192.168.93.88]:3001 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwfVmMvq4ZuLciMlkjVCyygOWkGCPPzcz72jsM/SK7KqFeGooSCQNazGkAXHC8tcYIy25ihuMB19kkfiVa1uFehOekuoBLAjnYXzIlDUG/WaUbyLXjQ51c6QwJ2l8KUjAv8ccyBsd7ufl5ckvJmMTFKVl3Wx8bz1MD4scGVMh1cJ2IRdcPWRmY56iZP2jQdzgYX0Wi/2nJ04JJ4xXXFRBJ+MObmrAB3AhNvbV0QDuCHghLo/z5N/ZmzJa+zEHZh8uOzXHFmo4PKblGX3bVuPR9oohS+l1QcdQi7bF+YMVcxOkP0z0TwTleoMqIOXxjckhPHJ48oM4N5OZldritypDP

  valuesFrom:
  - kind: Secret
    name: "argocd-values"
    optional: false
