apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-values
  namespace: argocd
spec:
  encryptedData:
    argocdServerAdminPassword: AgAmOH3Z+wee6K0E8N1KPO4I3+2Q2n5q+x0DvoLsWqPBDhLQ7KylvAZpM0V9aEg0hE6ae4pTU2jPgiobbhJEeRz2PPfg2M4ff0+IUjQI9HiEHSDSmuzXNcSHKq/PR5U9srTUVZYnPuXICkxMSTso7OAVNGkUMjMMSiB2SdbyKd0SNZn5L1ZnxPm3WQhqAQf3qYdIpztADqovJiDlfue8hGInxv54GPq4rjDN3RGMC6lWx4ZhUWeGJTnTvDZYoipN7XwWjU7IRNG2Tw52Xp+q47dzatCx3S+QurpZzCaVEVBENGqtokHf/njLCPghSawN2QJJbUdYSsDGRSK9W5zarkGcSgYWSurBBjhHSevn6eYsvyc4cxhTi19ZYdBWOKpq9mziIQMWdUOpK3muZ1fJvPWCpb4otbNi6Pao6+xlZHsYZk8hUuHtFK8KJo8A/dxQQu9DuSIE1q5wXbMrh3pCKipC/+amXUPUR5y+vHe2SlpGgcnYRY9ZAJyubZkwZ3S25UlxzoXxiHc5mnzEup+U99sTm4LYo4rgsEMKk2sk8QgpElV3myYs6t3BmpFVH2KD70tXUQE5X9ITee7HVbuSofWs9gCUYonhlkd6U2eMsZrZLIkE9Q7ybwzYnux5AG60CVUHUY1KeKW633GxZhpygc08ipjNmHwh9PVFHawOdRkOWF4+pjgKisDcspMvqLQ+eJC20YQspRCcwh2Y7ZcqrpRhZ/PzH3JOmUnS6S5Yruuo6Xdcf2uSl+E97y5UNTeyyH5FBfwGgtfP7GDLo0M=
    dexGithubClientSecret: AgB4LWPQFSyIPnIYkmX8bARVh6JWyH7PdD2DK32li4GlAfNvoCql0Ijbs5Z4rvEHYFuXXOWggDWrSRp7A1YupnrKvlwlcY2qePiN61AF+wcMuEnUA9vfNtRXMMJ30AEtsu8ldzf6rP9cSOC2QBKcZdMVQzJVuXNNemULKUxk29/175BfokvpQAVDOWfWFv7s2ATev3THjwG48c7UkA5Paww47hBJ4r/wg/drBiAn7XzkkZ5iXS1daQwhwFu1XyiTY5CAqOaNarMAjmyU/nwmg1yB3kAK6UUVVsbc2ZmfQosJnvYTzGEakNfHL7kAri9nDgl1GQgh/klvos0OLYOQtxevpChfABKFBgsWXhmxE0Oz3GuSPh4uAQ6CBcBHa0ggmiMkqh7OUk2sf/Qa1z5atY1K/hNGeWe2O6oftEOm7I9onzBjYa6qOzXvK1x1jf4r5uWr6Aqx5EVO7ms3WvdFLp2nD0T9A+IJeXTxyNQDj0bQC6iM9QFF76HSkGOHGlYHMFoRJL7PvXAbKO+YHQ3ZYgYMR/5kwVL+KWjPSGW564P/+B10DNVCqRd3kAZKEQMksbxUjM7LgektBmpilEgMdRN+Fj0nBVzZzrzzwsJAmm01eOQisUJ9laThDn97pDT5W/Al6baMVBndgAipmYI3YZ4i6zOAqzbrFr5rSXgNs+uQkmWq8y0lNRUXe1kG+uURfIPjH1y93b7IT19e8IIzcdzdctjlVd4vsDA2WuZgvYS6lT9/el4XgJNE
  template:
    metadata:
      name: argocd-values
      namespace: argocd
    type: Opaque

