---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "2.14.7"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: false

    controller:
      enableStatefulSet: true

    server:
      extraArgs:
        - --insecure
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: contour
          ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt
        hosts: ["argocd.tools.kilchhofer.info"]
        tls:
          - secretName: argocd-tls
            hosts: ["argocd.tools.kilchhofer.info"]

      config:
        url: https://argocd.tools.kilchhofer.info

      additionalApplications:
        - name: k8s-gitops-services
          namespace: argocd
          destination:
            server: 'https://kubernetes.default.svc'
          project: base
          syncPolicy:
            automated: {}
          source:
            path: argocd
            repoURL: 'git@github.com:mkilchhofer/k8s-gitops-services.git'
            targetRevision: main
            directory:
              recurse: true

      additionalProjects:
        - name: base
          namespace: argocd
          description: Projects provisioned together with Argo CD (infra deployment)
          clusterResourceWhitelist:
          - group: '*'
            kind: '*'
          destinations:
          - namespace: '*'
            server: 'https://kubernetes.default.svc'
          sourceRepos:
          - '*'

  valuesFrom:
  - kind: Secret
    name: "argocd-values"
    optional: false
