---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "2.12.0"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: false
    server:
      extraArgs:
        - --insecure
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: contour
          ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt
        hosts: ["argocd.tools.kilchhofer.info"]
        tls:
          - secretName: argocd-tls
            hosts: ["argocd.tools.kilchhofer.info"]
  valuesFrom:
  - kind: Secret
    name: "argocd-values"
    optional: false
