---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "2.12.0"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: false
