apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: base
  syncPolicy:
    automated: {}
  source:
    path: argocd
    repoURL: 'git@github.com:mkilchhofer/k8s-gitops-services.git'
    targetRevision: main
    directory:
      recurse: true
