---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: eventrouter
  namespace: monitoring
spec:
  releaseName: eventrouter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: eventrouter
    version: "0.2.3"
  values:
    sink: "stdout"
