---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: eventrouter
  namespace: monitoring
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/eventrouter-0.2.2.tgz
  valuesContent: |-
    sink: "stdout"
