---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: eventrouter
  namespace: monitoring
spec:
  releaseName: eventrouter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: eventrouter
    version: "0.3.0"
  values:
    sink: "stdout"
    resources:
      limits:
       cpu: 50m
       memory: 64Mi
      requests:
       cpu: 10m
       memory: 16Mi
