apiVersion: v1
kind: Namespace
metadata:
  name: traefik-internal
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-internal
  namespace: traefik-internal
spec:
  chart: stable/traefik
  version: "1.77.0"
  set:
    rbac.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
  valuesContent: |-
    dashboard:
      enabled: true
      domain: traefik.k8s.kilchhofer.info
      ingress:
        annotations:
          kubernetes.io/ingress.class: traefik-internal
          traefik.ingress.kubernetes.io/redirect-entry-point: https
    kubernetes:
      ingressClass: traefik-internal
    ssl:
      enabled: "true"
      enforced: "true"
      defaultCert: <replace_with_base64_encoded_pem>
      defaultKey: <replace_with_base64_encoded_pem>
