---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: chartmuseum-local-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://chartmuseum.tools.kilchhofer.info/
  timeout: 3m
