---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 10m
  url: https://fluent.github.io/helm-charts
  timeout: 3m
