apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  chart:
    git: https://github.com/mkilchhofer/charts.git
    ref: sealed-secrets-ingress
    path: stable/sealed-secrets
  values:
    crd:
      create: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik-internal
        traefik.ingress.kubernetes.io/redirect-entry-point: https
      hosts:
        - sealed-secrets.k8s.kilchhofer.info
