apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb-system
  rollback:
    enable: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: "0.1.15"
  values:
    configInline:
      address-pools:
      - name: default
        protocol: bgp
        addresses:
        - 192.168.93.10-192.168.93.90
      peers:
      - peer-address: 192.168.92.1
        peer-asn: 64512
        my-asn: 64513
    controller:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    speaker:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
