apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb-system
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: "0.11.1"
  values:
    configInline:
      address-pools:
      - name: default
        protocol: bgp
        addresses:
        - 192.168.93.10-192.168.93.90
      peers:
      - peer-address: 192.168.92.1
        peer-asn: 64512
        my-asn: 64513
