---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-event-exporter
  namespace: monitoring
spec:
  releaseName: kubernetes-event-exporter
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: kubernetes-event-exporter
      version: "1.0.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: opsgenie/kubernetes-event-exporter
      tag: 0.9
    config:
      logLevel: warn
      logFormat: pretty
      receivers:
        - name: "dump"
          file:
            path: "/dev/stdout"
            layout:
              message: "{{ .Message }}"
              reason: "{{ .Reason }}"
              type: "{{ .Type }}"
              count: "{{ .Count }}"
              kind: "{{ .InvolvedObject.Kind }}"
              name: "{{ .InvolvedObject.Name }}"
              namespace: "{{ .Namespace }}"
              component: "{{ .Source.Component }}"
              host: "{{ .Source.Host }}"
      route:
        routes:
          - match:
              - receiver: "dump"
            drop:
              - type: "Normal"
