---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-event-exporter
  namespace: monitoring
spec:
  releaseName: kubernetes-event-exporter
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: kubernetes-event-exporter
      version: "1.2.0-leaderelection.2"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-local-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      registry: ghcr.io
      repository: opsgenie/kubernetes-event-exporter
      tag: v0.10
    replicaCount: 2
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
      requests:
        cpu: 10m
        memory: 25Mi
    config:
      logLevel: warn
      logFormat: pretty
      receivers:
        - name: "dump"
          stdout:
            layout:
              message: "{{ .Message }}"
              reason: "{{ .Reason }}"
              type: "{{ .Type }}"
              count: "{{ .Count }}"
              kind: "{{ .InvolvedObject.Kind }}"
              name: "{{ .InvolvedObject.Name }}"
              namespace: "{{ .Namespace }}"
              component: "{{ .Source.Component }}"
              host: "{{ .Source.Host }}"
      route:
        routes:
          - match:
              - receiver: "dump"
            drop:
              - type: "Normal"
