apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "18.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 1m
  values:
    alertmanager:
      enabled: false
    grafana:
      enabled: false

    coreDns:
      enabled: false
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubelet:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "iscsi-manual"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
