apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-data-provisioner
  namespace: storage
spec:
  releaseName: nfs-data-provisioner
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.7"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-provisioner
        namespace: flux-system
      interval: 1m
  values:
    nameOverride: nfs-data-provisioner
    nfs:
      server: "nfs-data.ma.kilchhofer.info"
      path: "/volume1/kubernetes/nfs-data"
    storageClass:
      defaultClass: true
      name: "nfs-data"
      provisionerName: cluster.local/nfs-data-provisioner
