apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-data-provisioner
  namespace: storage
spec:
  releaseName: nfs-data-provisioner
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.6"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-provisioner
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: v4.0.2

    nameOverride: nfs-data-provisioner

    nfs:
      server: "nfs-data.ma.kilchhofer.info"
      path: "/volume1/kubernetes/nfs-data"

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 16Mi

    storageClass:
      defaultClass: true
      name: "nfs-data"
      provisionerName: cluster.local/nfs-data-provisioner
