apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: projectcontour-internal
  namespace: projectcontour-internal
spec:
  releaseName: projectcontour-internal
  maxHistory: 3
  skipCRDs: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: contour
    version: "2.3.4"
  values:
    envoy:
      useHostPort: false
      containerPorts:
        http: 8080
        https: 8443
      service:
        loadBalancerIP: 192.168.93.83
      containerSecurityContext:
        runAsUser: 1001

    prometheus:
      serviceMonitor:
        enabled: true
