apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: projectcontour-internal
  namespace: projectcontour-internal
spec:
  releaseName: projectcontour-internal
  rollback:
    enable: false
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: contour
    version: "1.1.3"
  values: {}
