---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: olm-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_olm-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: olm
  namespace: flux-system
spec:
  dependsOn:
    - name: olm-crds
      namespace: flux-system
  interval: 10m0s
  path: ./_olm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
