apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCIRyojtixJG6IYq+VHi34cfYaLtpK+TLolvWMfHKWzVf4oAnuZ92/F9ClkiqxrvVUNEbSerx8DqJO85dok6fHwnsePKQ4TqaxPmKuroar7RgyJ1YOUDqzwfEnT/lTdgNODiDosOj5OVZypbk7gMSvOXILlHDUJCbX/msnAqUaStEo4N2vEUpdXoqc6HAtTbNcwwMmJ/AzWcPMsCZV5NtQnLgkQTzeGFM9oXoxd2Gt8jIaproXySe2I1cedlGfallRuozsQQINBDA+kzPEgrtz8ngtP1q5c+gsf0fzPmmfwbLxrF3DEJeIFEtbvUt/kcETxXydfKIoXoGKrYuVjC+3rZ03qzNHfBt1Xh6wMsXLgz2stpLLIpDrdAqwAvBA6RT9r5p/XUllqI5dRoawdFS1XSTsfVN5aea9sjo2S9TR3RMwFzGeYlblC0TOpt7XU1GVZaUwqjUZr+Zisfc4VrBldBuunTPGcYq9adzPEEpaCXU2nldnH5O+A4zKuHYL9e9CfAHobg6auVkkKRC1bwFw6tdxDOobY2B2ip6O7XmWFcuAJg/vkQtAW21NW6Ab/AaUFxOV7GMGTb0qIlRzawFwiYhJ/EzgyV2MQd0v+Q/ZE525ErC/0E7yoyLBOBhxCYF7uxTuhRHpJt9AySzULrKvq7AiVxhDjek44tbhEqLCLBIvDS3rpXF5Rclq/LUI33dN6/rd8fPiInpVdUVSPFjgjFNXi8c8/sVJlbWWydV3AUjzuswO6vR0p
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

