apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: ingress
spec:
  releaseName: metallb-system
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "2.3.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1m
  values:
    global:
      imageRegistry: quay.io
    configInline:
      address-pools:
      - name: default
        protocol: bgp
        addresses:
        - 192.168.93.10-192.168.93.90
      peers:
      - peer-address: 192.168.92.1
        peer-asn: 64512
        my-asn: 64513
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.6
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.6
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
