apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: projectcontour-internal
  namespace: ingress
spec:
  releaseName: projectcontour-internal
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: contour
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1m
  values:
    envoy:
      image:
        repository: envoyproxy/envoy
        tag: v1.16.2
      useHostPort: false
      containerPorts:
        http: 8080
        https: 8443
      service:
        loadBalancerIP: 192.168.93.83
      containerSecurityContext:
        runAsUser: 1001
    contour:
      image:
        repository: projectcontour/contour
        tag: v1.11.0

    prometheus:
      serviceMonitor:
        enabled: true

    defaultBackend:
      enabled: true

      image:
        registry: k8s.gcr.io
        repository: defaultbackend-amd64
        tag: "1.5"

      livenessProbe:
        httpGet:
          path: /healthz
      readinessProbe:
        httpGet:
          path: /healthz
