---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: ingress
spec:
  releaseName: traefik-external
  maxHistory: 3
  interval: 5m
  install:
    skipCRDs: true
  chart:
    spec:
      chart: traefik
      version: "9.14.3"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"

    service:
      spec:
        externalTrafficPolicy: Local
        loadBalancerIP: "192.168.93.90"

    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: false

    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik-external"

    logs:
      general:
        # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: DEBUG
