---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  releaseName: rancher
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: "2.6.0"
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
      interval: 1m
  values:
    hostname: r.kilchhofer.info
    ingress:
      tls:
        source: letsEncrypt
    letsEncrypt:
      email: postmaster+rancher@kilchhofer.info
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
