apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storage-nfs-data
  namespace: persistent-storage
spec:
  releaseName: storage-nfs-data
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.2"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-provisioner
        namespace: flux-system
      interval: 1m
  values:
    nfs:
      server: "nfs-data.ma.kilchhofer.info"
      path: "/volume1/kubernetes/nfs-data"
    storageClass:
      defaultClass: true
      name: "nfs-data"
      provisionerName: cluster.local/storage-nfs-data-nfs-client-provisioner
