---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  maxHistory: 3
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: "v0.16.1"
  values:
    installCRDs: "true"
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53
    prometheus:
      servicemonitor:
        enabled: true
