---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  maxHistory: 3
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: "v1.0.4"
  values:
    installCRDs: false
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53
    prometheus:
      servicemonitor:
        enabled: true
